### ISSUE TITLE
a11y and a11y/personalization 

### ISSUE THREAD

**Issue by blackfalcon** [blackfalcon/developing-design-systems#8]
Supporting accessibility is hard. While having a design system and coded elements can help bridge gaps in this space, it's not 100% the solution. 

Let's talk about lessons learned in supporting a11y with each respective design system.

**Comment by Westbrook** [comment]
Some background reading: 
- https://dev.to/westbrook/who-doesnt-love-some-s-3de0
- https://dev.to/westbrook/testing-accessibility-with-shadow-roots-55cm
- https://leobalter.github.io/cross-root-aria-delegation/
- If I really kill it this week, I _might_ have a draft of the reciprocal "reflection" API proposal based on https://github.com/Westbrook/custom-element-proposals/tree/aria-discussion#reflection-as-a-oposite-of-delegation
- Also, you can support some of this at dev time: https://github.com/adobe/spectrum-web-components/blob/esbuild-2/packages/progress-bar/src/ProgressBar.ts#L104-L121
